### PR TITLE
Update exchanges.md

### PR DESCRIPTION
**Pull request by GlenCooper**
# Description
Looks like big.one dropped LBC.  If not, the current link on this page is broken, goes to a 404 page.
Removed hyperlink to https://big.one

### Fixes #

### CODE REVIEW

**Comment by GlenCooper** [comment]
Screenshot from 2020-03-20 01-11-47

**Comment by GlenCooper** [comment]
I searched their trading pairs, found no match for LBC

**Comment by tzarebczan** [comment]
Thank you! Can we show you some [appreciation](https://lbry.com/faq/appreciation)?

**Comment by GlenCooper** [comment]
sent email to hello

**Pull request merged**
