### PR TITLE
fix format table

### LINKED ISSUE #1241: Table formatting is off on naming faq
See https://lbry.com/faq/naming and compare to github markdown

### PR DESCRIPTION
**Pull request by ykris45**
### Description
AFTER
image
BEFORE
image
FIXES #1241

### CODE REVIEW

**Comment by kauffj** [comment]
@ykris45 I'm unable to get this to happen at any width. Can you reopen with your browser details if it's still happening?

**Comment by tzarebczan** [comment]
It's happening here too: https://lbry.com/faq/privacy-and-data
image

naming FAQ: 
image

**Comment by ykris45** [comment]
image

@kauffj use that same variables as my PR on privacy and data FAQ

**Comment by kauffj** [comment]
Sorry for letting this sit, but I still don't understand how to get it to happen. Tried your URLs and varying window width @tzarebczan.

This is definitely not the right answer though, so I'm going to close it. The right answer may be to give `td` a min-width, but that could have broader consequences.

**Pull request closed without merging**
