### PR TITLE
Introduce Telegram bot to the FAQ page

### PR DESCRIPTION
**Pull request by danger89**
### Description

Introduce the (Telegram) bot to the FAQ page of lbry.com. As promised to fix within the Hacktoberfest!

Just in time. 

Kind Regards,
Melroy van den Berg

### CODE REVIEW

**Comment by tzarebczan** [comment]
Thanks for the write-up! I think we can combine this section with the tipbots and just call it bots.  Can you make that change? 

I'll DM you the info for the shirt!

**Comment by danger89** [comment]
@tzarebczan No problemo!

**Comment by danger89** [comment]
Lgtm

**Comment by danger89** [comment]
Thanks for your additional changes

**Pull request merged**
