### PR TITLE
Added featured images, and the help lbry save crypto banner

### PR DESCRIPTION
**Pull request by iamflorencejay**
### Description

- Added Help LBRY SAVE CRYPTO banner
- Added featured images
- Added some stylesheet changes

### CODE REVIEW

**Comment by kauffj** [comment]
I'm still interested in a version of this just with the logos

**Comment by iamflorencejay** [comment]
Okay. So I will remove it.

**Comment by iamflorencejay** [comment]
@kauffj done

**Comment by kauffj** [comment]
merged, thank you @iamflorencejay! I sent a tip to your channel too :)

**Pull request merged**
