### PR TITLE
Update standalone-wallet.md

### PR DESCRIPTION
**Pull request by iamflorencejay**
### Description

Updating standalone wallet to 2 wallets.

### CODE REVIEW

**Comment by tzarebczan** [comment]
Do you have more information about this wallet? Have you tried and tested it?

**Comment by iamflorencejay** [comment]
@tzarebczan Yes. It is like coinomi or trust wallet that you can add your 12 digit phrase to work. And it is also the company that handles coinex.

image

**Comment by iamflorencejay** [comment]
It is on Google play and app store btw.

**Comment by tzarebczan** [comment]
Able to send/receive as expected? Does it have the legacy (regular b * addresses?)?

**Comment by LaroTayoGaming** [comment]
yep. it is produced by default.

**Pull request merged**
