### PR TITLE
Create uganda.php

### PR DESCRIPTION
**Pull request by ceoger**
created this page for the Uganda hive for their upcoming and future meetups/activities

### Fixes #

### CODE REVIEW

**Comment by ceoger** [comment]
@jsigwart kindly take a look and merge when you can, also, it'll be great if you can update the image :)

**Comment by kauffj** [comment]
@Invariant-Change what about getting these pages up on lbry.org and giving @ceoger the ability to edit/manage pages there directly via UI?

**Comment by Invariant-Change** [comment]
Ralph/CoolGuy has control of lbry.org If you ask him, I'm sure he'll give you access.

**Comment by jsigwart** [comment]
I merged this since their meetup is soon. Will get folks on the same page.

**Comment by jsigwart** [comment]
@Invariant-Change ETA on lbry.org going live so Clement can add pages to it?

**Comment by Invariant-Change** [comment]
The discussion with Jeremy, was that LBRY Social website and Discord were to become the Swarm website/chat. If that is still the plan, it's a simple update. Clement has access to LBRY Social so can add there at any time.

image

**Pull request merged**
