### PR TITLE
Updated preview video

### PR DESCRIPTION
**Pull request by NetOperatorWibby**
'nuff said

### CODE REVIEW

**Comment by tzarebczan** [comment]
Thanks Paul. Seems a bit too fast - can you try 2.5 seconds...that's what I've used before (should have mentioned this).

Also, Chrome won't play the current one on lbry.com for me at time...I have to refresh a bunch. Any ideas?

**Comment by NetOperatorWibby** [comment]
Chrome probably has the original video cached. I'll update when I get to my desktop again.

**Comment by NetOperatorWibby** [comment]
Updated the video

**Comment by tzarebczan** [comment]
Thanks, looks good! Let's see how it looks on lbry.com now.

**Pull request merged**
