### PR TITLE
The Help LBRY Save Crypto Update

### PR DESCRIPTION
**Pull request by iamflorencejay**
### Description

Added the HELP LBRY SAVE CRYPTO campaign, and added the "as featured on" on the bottom.

### CODE REVIEW

**Comment by kauffj** [comment]
@iamflorencejay adding news logos is an interesting/good idea. We'd accept this PR and send an LBC tip if you can:

- Use grayscale logos
- Drop the links to the articles
- Make the logos a standalone row
- Add New York Times, National Public Radio, Nasdaq, Forbes, and bitcoin.com logos
- Ensure the PR only contains the logo changes, none of the other changes

**Comment by iamflorencejay** [comment]
@kauffj oh wowie! Updating this later. it's like 5am here.

**Comment by iamflorencejay** [comment]
Screenshot_2021-04-30_09-50-29
Here is the preview @kauffj

**Comment by iamflorencejay** [comment]
@kauffj can I ask what are those links to add in the code?

**Comment by iamflorencejay** [comment]
im done :D

**Comment by kauffj** [comment]
This is better but:

1. Other changes must be stripped out of this PR, like the helplbrysavecrypto header.
1. Remove the links to the articles
1. It shouldn't be an h1 (maybe h3 or h4?)
1. Put crypto publications and reclaim the net last

**Pull request closed without merging**
